<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="litter_bot">

  <!-- Arguments -->
  <xacro:arg name="use_sim" default="true"/>
  <xacro:arg name="use_camera" default="true"/>

  <!-- Properties -->
  <xacro:property name="wheel_radius" value="0.033"/>
  <xacro:property name="wheel_width" value="0.018"/>
  <xacro:property name="wheel_separation" value="0.287"/>
  <xacro:property name="base_x" value="0.281"/>
  <xacro:property name="base_y" value="0.306"/>
  <xacro:property name="base_z" value="0.141"/>
  
  <!-- Materials -->
  <material name="black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>
  <material name="dark_grey">
    <color rgba="0.3 0.3 0.3 1.0"/>
  </material>
  <material name="light_grey">
    <color rgba="0.7 0.7 0.7 1.0"/>
  </material>
  <material name="white">
    <color rgba="1.0 1.0 1.0 1.0"/>
  </material>
  <material name="orange">
    <color rgba="1.0 0.5 0.0 1.0"/>
  </material>
  <material name="blue">
    <color rgba="0.2 0.2 0.8 1.0"/>
  </material>

  <!-- ==================== BASE FOOTPRINT ==================== -->
  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 0.010" rpy="0 0 0"/>
  </joint>

  <!-- ==================== BASE LINK ==================== -->
  <link name="base_link">
    <visual>
      <origin xyz="-0.064 0 0.0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_x} ${base_y} ${base_z}"/>
      </geometry>
      <material name="dark_grey"/>
    </visual>
    <collision>
      <origin xyz="-0.064 0 0.047" rpy="0 0 0"/>
      <geometry>
        <box size="${base_x} ${base_y} ${base_z}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1.3729096"/>
      <inertia ixx="0.0142" ixy="0" ixz="0" iyy="0.0142" iyz="0" izz="0.0238"/>
    </inertial>
  </link>

  <!-- ==================== WHEELS ==================== -->
  <xacro:macro name="wheel" params="prefix y_offset">
    <link name="${prefix}_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="1.57 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="1.57 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0"/>
        <mass value="0.1"/>
        <inertia ixx="0.00005" ixy="0" ixz="0" iyy="0.00005" iyz="0" izz="0.00009"/>
      </inertial>
    </link>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_wheel_link"/>
      <origin xyz="0 ${y_offset} 0.023" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <xacro:wheel prefix="left" y_offset="${wheel_separation/2}"/>
  <xacro:wheel prefix="right" y_offset="${-wheel_separation/2}"/>

  <!-- ==================== CASTER WHEEL ==================== -->
  <link name="caster_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.01"/>
      </geometry>
      <material name="dark_grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.01"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="0.01"/>
      <inertia ixx="0.000001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.000001"/>
    </inertial>
  </link>

  <joint name="caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_link"/>
    <origin xyz="-0.177 0 -0.013" rpy="0 0 0"/>
  </joint>

  <!-- ==================== LIDAR ==================== -->
  <link name="base_scan">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.0508" length="0.055"/>
      </geometry>
      <material name="dark_grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.0508" length="0.055"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="0.125"/>
      <inertia ixx="0.00008" ixy="0" ixz="0" iyy="0.00008" iyz="0" izz="0.00012"/>
    </inertial>
  </link>

  <joint name="scan_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_scan"/>
    <origin xyz="-0.064 0 0.122" rpy="0 0 0"/>
  </joint>

  <!-- ==================== IMU ==================== -->
  <link name="imu_link"/>

  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 0.068" rpy="0 0 0"/>
  </joint>

  <!-- ==================== CAMERA (RealSense D435i) ==================== -->
  <xacro:if value="$(arg use_camera)">
    <link name="camera_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="0.025 0.09 0.025"/>
        </geometry>
        <material name="light_grey"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="0.025 0.09 0.025"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0"/>
        <mass value="0.072"/>
        <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
      </inertial>
    </link>

    <joint name="camera_joint" type="fixed">
      <parent link="base_link"/>
      <child link="camera_link"/>
      <origin xyz="0.064 0 0.1" rpy="0 0.3 0"/>
    </joint>

    <link name="camera_rgb_frame"/>
    <joint name="camera_rgb_joint" type="fixed">
      <parent link="camera_link"/>
      <child link="camera_rgb_frame"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="camera_depth_frame"/>
    <joint name="camera_depth_joint" type="fixed">
      <parent link="camera_link"/>
      <child link="camera_depth_frame"/>
      <origin xyz="0 0.0175 0" rpy="0 0 0"/>
    </joint>

    <link name="camera_rgb_optical_frame"/>
    <joint name="camera_rgb_optical_joint" type="fixed">
      <parent link="camera_rgb_frame"/>
      <child link="camera_rgb_optical_frame"/>
      <origin xyz="0 0 0" rpy="-1.5708 0 -1.5708"/>
    </joint>

    <link name="camera_depth_optical_frame"/>
    <joint name="camera_depth_optical_joint" type="fixed">
      <parent link="camera_depth_frame"/>
      <child link="camera_depth_optical_frame"/>
      <origin xyz="0 0 0" rpy="-1.5708 0 -1.5708"/>
    </joint>
  </xacro:if>

  <!-- ==================== OPENMANIPULATOR-X ARM ==================== -->
  <!-- Arm base mount on top of the robot -->
  <link name="arm_base_link">
    <visual>
      <origin xyz="0 0 0.019" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 0.038"/>
      </geometry>
      <material name="dark_grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0.019" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 0.038"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0.019"/>
      <mass value="0.1"/>
      <inertia ixx="0.00005" ixy="0" ixz="0" iyy="0.00005" iyz="0" izz="0.00005"/>
    </inertial>
  </link>

  <joint name="arm_base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="arm_base_link"/>
    <origin xyz="0.05 0 0.141" rpy="0 0 0"/>
  </joint>

  <!-- Link 1 -->
  <link name="link1">
    <visual>
      <origin xyz="0 0 0.0185" rpy="0 0 0"/>
      <geometry>
        <box size="0.045 0.045 0.037"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <collision>
      <origin xyz="0 0 0.0185" rpy="0 0 0"/>
      <geometry>
        <box size="0.045 0.045 0.037"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0.0185"/>
      <mass value="0.098"/>
      <inertia ixx="0.00002" ixy="0" ixz="0" iyy="0.00002" iyz="0" izz="0.00002"/>
    </inertial>
  </link>

  <joint name="joint1" type="revolute">
    <parent link="arm_base_link"/>
    <child link="link1"/>
    <origin xyz="0 0 0.038" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-2.827" upper="2.827" effort="1.0" velocity="4.8"/>
  </joint>

  <!-- Link 2 -->
  <link name="link2">
    <visual>
      <origin xyz="0.024 0 0.064" rpy="0 0 0"/>
      <geometry>
        <box size="0.04 0.04 0.128"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <origin xyz="0.024 0 0.064" rpy="0 0 0"/>
      <geometry>
        <box size="0.04 0.04 0.128"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0.024 0 0.064"/>
      <mass value="0.138"/>
      <inertia ixx="0.00024" ixy="0" ixz="0" iyy="0.00024" iyz="0" izz="0.00002"/>
    </inertial>
  </link>

  <joint name="joint2" type="revolute">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 0 0.037" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-1.79" upper="1.57" effort="1.0" velocity="4.8"/>
  </joint>

  <!-- Link 3 -->
  <link name="link3">
    <visual>
      <origin xyz="0.06 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.12 0.035 0.035"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <origin xyz="0.06 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.12 0.035 0.035"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0.06 0 0"/>
      <mass value="0.098"/>
      <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00012" iyz="0" izz="0.00012"/>
    </inertial>
  </link>

  <joint name="joint3" type="revolute">
    <parent link="link2"/>
    <child link="link3"/>
    <origin xyz="0.024 0 0.128" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-0.94" upper="1.39" effort="1.0" velocity="4.8"/>
  </joint>

  <!-- Link 4 -->
  <link name="link4">
    <visual>
      <origin xyz="0.045 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.09 0.035 0.035"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <origin xyz="0.045 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.09 0.035 0.035"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0.045 0 0"/>
      <mass value="0.072"/>
      <inertia ixx="0.000007" ixy="0" ixz="0" iyy="0.00006" iyz="0" izz="0.00006"/>
    </inertial>
  </link>

  <joint name="joint4" type="revolute">
    <parent link="link3"/>
    <child link="link4"/>
    <origin xyz="0.124 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-1.79" upper="2.04" effort="1.0" velocity="4.8"/>
  </joint>

  <!-- Gripper Base -->
  <link name="gripper_base_link">
    <visual>
      <origin xyz="0.015 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.03 0.04 0.025"/>
      </geometry>
      <material name="dark_grey"/>
    </visual>
    <collision>
      <origin xyz="0.015 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.03 0.04 0.025"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0.015 0 0"/>
      <mass value="0.03"/>
      <inertia ixx="0.000002" ixy="0" ixz="0" iyy="0.000003" iyz="0" izz="0.000003"/>
    </inertial>
  </link>

  <joint name="gripper_base_joint" type="fixed">
    <parent link="link4"/>
    <child link="gripper_base_link"/>
    <origin xyz="0.09 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Left Gripper Finger -->
  <link name="gripper_left_link">
    <visual>
      <origin xyz="0.02 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.04 0.01 0.02"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <origin xyz="0.02 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.04 0.01 0.02"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0.02 0 0"/>
      <mass value="0.01"/>
      <inertia ixx="0.0000003" ixy="0" ixz="0" iyy="0.0000015" iyz="0" izz="0.0000015"/>
    </inertial>
  </link>

  <joint name="gripper_left_joint" type="prismatic">
    <parent link="gripper_base_link"/>
    <child link="gripper_left_link"/>
    <origin xyz="0.03 0.015 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-0.01" upper="0.019" effort="1.0" velocity="1.0"/>
  </joint>

  <!-- Right Gripper Finger -->
  <link name="gripper_right_link">
    <visual>
      <origin xyz="0.02 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.04 0.01 0.02"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <origin xyz="0.02 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.04 0.01 0.02"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0.02 0 0"/>
      <mass value="0.01"/>
      <inertia ixx="0.0000003" ixy="0" ixz="0" iyy="0.0000015" iyz="0" izz="0.0000015"/>
    </inertial>
  </link>

  <joint name="gripper_right_joint" type="prismatic">
    <parent link="gripper_base_link"/>
    <child link="gripper_right_link"/>
    <origin xyz="0.03 -0.015 0" rpy="0 0 0"/>
    <axis xyz="0 -1 0"/>
    <limit lower="-0.01" upper="0.019" effort="1.0" velocity="1.0"/>
  </joint>

  <!-- End Effector Link (for MoveIt) -->
  <link name="end_effector_link"/>

  <joint name="end_effector_joint" type="fixed">
    <parent link="gripper_base_link"/>
    <child link="end_effector_link"/>
    <origin xyz="0.06 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Collection Bin -->
  <link name="collection_bin_link">
    <visual>
      <origin xyz="0 0 0.05" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <collision>
      <origin xyz="0 0 0.05" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0.05"/>
      <mass value="0.05"/>
      <inertia ixx="0.00008" ixy="0" ixz="0" iyy="0.00008" iyz="0" izz="0.00008"/>
    </inertial>
  </link>

  <joint name="collection_bin_joint" type="fixed">
    <parent link="base_link"/>
    <child link="collection_bin_link"/>
    <origin xyz="-0.15 0 0.141" rpy="0 0 0"/>
  </joint>

  <!-- ==================== GAZEBO PLUGINS ==================== -->
  <xacro:if value="$(arg use_sim)">
    <!-- Differential Drive -->
    <gazebo>
      <plugin name="diff_drive" filename="libgazebo_ros_diff_drive.so">
        <ros>
          <namespace>/</namespace>
        </ros>
        <update_rate>30</update_rate>
        <left_joint>left_wheel_joint</left_joint>
        <right_joint>right_wheel_joint</right_joint>
        <wheel_separation>${wheel_separation}</wheel_separation>
        <wheel_diameter>${wheel_radius*2}</wheel_diameter>
        <max_wheel_torque>20</max_wheel_torque>
        <max_wheel_acceleration>1.0</max_wheel_acceleration>
        <command_topic>cmd_vel</command_topic>
        <publish_odom>true</publish_odom>
        <publish_odom_tf>true</publish_odom_tf>
        <publish_wheel_tf>false</publish_wheel_tf>
        <odometry_topic>odom</odometry_topic>
        <odometry_frame>odom</odometry_frame>
        <robot_base_frame>base_footprint</robot_base_frame>
      </plugin>
    </gazebo>

    <!-- LIDAR -->
    <gazebo reference="base_scan">
      <sensor type="ray" name="lds_lfcd_sensor">
        <pose>0 0 0 0 0 0</pose>
        <visualize>false</visualize>
        <update_rate>5</update_rate>
        <ray>
          <scan>
            <horizontal>
              <samples>360</samples>
              <resolution>1</resolution>
              <min_angle>0.0</min_angle>
              <max_angle>6.28319</max_angle>
            </horizontal>
          </scan>
          <range>
            <min>0.12</min>
            <max>3.5</max>
            <resolution>0.015</resolution>
          </range>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.01</stddev>
          </noise>
        </ray>
        <plugin name="gazebo_ros_lds_lfcd_controller" filename="libgazebo_ros_ray_sensor.so">
          <ros>
            <namespace>/</namespace>
            <remapping>~/out:=scan</remapping>
          </ros>
          <output_type>sensor_msgs/LaserScan</output_type>
          <frame_name>base_scan</frame_name>
        </plugin>
      </sensor>
    </gazebo>

    <!-- IMU -->
    <gazebo reference="imu_link">
      <sensor type="imu" name="imu">
        <always_on>true</always_on>
        <update_rate>200</update_rate>
        <imu>
          <angular_velocity>
            <x>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>2e-4</stddev>
              </noise>
            </x>
            <y>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>2e-4</stddev>
              </noise>
            </y>
            <z>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>2e-4</stddev>
              </noise>
            </z>
          </angular_velocity>
          <linear_acceleration>
            <x>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>1.7e-2</stddev>
              </noise>
            </x>
            <y>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>1.7e-2</stddev>
              </noise>
            </y>
            <z>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>1.7e-2</stddev>
              </noise>
            </z>
          </linear_acceleration>
        </imu>
        <plugin name="imu_plugin" filename="libgazebo_ros_imu_sensor.so">
          <ros>
            <namespace>/</namespace>
            <remapping>~/out:=imu</remapping>
          </ros>
          <initial_orientation_as_reference>false</initial_orientation_as_reference>
          <frame_name>imu_link</frame_name>
        </plugin>
      </sensor>
    </gazebo>

    <!-- RGB-D Camera (RealSense D435i simulation) -->
    <xacro:if value="$(arg use_camera)">
      <gazebo reference="camera_link">
        <sensor type="depth" name="realsense_d435i">
          <update_rate>15</update_rate>
          <camera>
            <horizontal_fov>1.211</horizontal_fov>
            <image>
              <width>640</width>
              <height>480</height>
              <format>R8G8B8</format>
            </image>
            <depth_camera>
              <output>depths</output>
            </depth_camera>
            <clip>
              <near>0.1</near>
              <far>8.0</far>
            </clip>
            <noise>
              <type>gaussian</type>
              <mean>0.0</mean>
              <stddev>0.005</stddev>
            </noise>
          </camera>
          <plugin name="depth_camera_plugin" filename="libgazebo_ros_camera.so">
            <ros>
              <namespace>/camera</namespace>
              <remapping>image_raw:=color/image_raw</remapping>
              <remapping>camera_info:=color/camera_info</remapping>
              <remapping>depth/image_raw:=depth/image_raw</remapping>
              <remapping>depth/camera_info:=depth/camera_info</remapping>
              <remapping>points:=depth/points</remapping>
            </ros>
            <camera_name>realsense</camera_name>
            <frame_name>camera_depth_optical_frame</frame_name>
            <min_depth>0.1</min_depth>
            <max_depth>8.0</max_depth>
          </plugin>
        </sensor>
      </gazebo>
    </xacro:if>

    <!-- Joint State Publisher for arm -->
    <gazebo>
      <plugin name="gazebo_ros_joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
        <ros>
          <namespace>/</namespace>
          <remapping>~/out:=joint_states</remapping>
        </ros>
        <update_rate>50</update_rate>
        <joint_name>joint1</joint_name>
        <joint_name>joint2</joint_name>
        <joint_name>joint3</joint_name>
        <joint_name>joint4</joint_name>
        <joint_name>gripper_left_joint</joint_name>
        <joint_name>gripper_right_joint</joint_name>
      </plugin>
    </gazebo>

    <!-- Joint Position Controller for arm -->
    <gazebo>
      <plugin name="gazebo_ros_joint_pose_trajectory" filename="libgazebo_ros_joint_pose_trajectory.so">
        <ros>
          <namespace>/</namespace>
        </ros>
        <update_rate>50</update_rate>
      </plugin>
    </gazebo>
  </xacro:if>

</robot>

